/** The gate between a generated paper and a student's screen.
 *
 * `generateObject` guarantees the SHAPE of a paper — the fields exist and have
 * the right types — and nothing at all about whether the paper is usable. The
 * failures seen live are all schema-valid: a four-option question whose right
 * answer is not among the options, two identical choices, a ○× item whose
 * answer is 「はい」, a word-bank item answering with a word the bank does not
 * contain, a review reference reading "see the past paper".
 *
 * Each of those reaches the student as a question they cannot get right. So
 * items are checked here and dropped when they fail, and because the route
 * treats a paper left too short as a failed generation, a badly generated
 * paper is regenerated by the next provider rather than served.
 *
 * Every rejection carries a reason. They are logged, not shown — a student
 * should never learn that their paper had eleven questions and lost two —
 * but a silent filter is one nobody can tune.
 */

import type { SectionArchetype } from "./paper-format";
import { normalizeAnswer, type Quiz, type QuizItem, type QuizSection } from "./quiz";

export interface Rejection {
  section: number;
  item: number;
  reason: string;
}

const MARKS = /^[○◯〇⭕×✕✖❌]$/;

/** Strip readings and markers so two spellings of one answer compare equal. */
function bare(text: string): string {
  return normalizeAnswer(
    text.replace(/《[^》]*》/g, "").replace(/[（(][ぁ-ゖァ-ヶー]+[）)]/g, "").replace(/[【】]/g, ""),
  );
}

/** Does this answer plausibly come from the section's word bank?
 *
 * Loose on purpose. The bank prints dictionary forms (「終わります」) and the
 * answer is the conjugated form the sentence needs (「終わった」), so they
 * share a stem and little else. Requiring an exact match would reject every
 * correct answer in the most common section on the paper; requiring a shared
 * opening character catches the answer that came from nowhere.
 */
function fromBank(answer: string, bank: string[]): boolean {
  const target = bare(answer);
  if (!target) return false;
  // The leading character, and only that.
  //
  // A Japanese verb conjugates after its stem: 行きます, 行った and 行こう all
  // open with 行; します, したら and して all open with し. Anything more is
  // too strict — measured live, a two-character anchor rejected したら against
  // します and 行き against 行きます, which are the correct answers. This check
  // is here to catch an answer that came from nowhere, not to conjugate.
  const anchor = (word: string) => bare(word).slice(0, 1);
  const targetAnchor = anchor(target);
  return bank.some((word) => {
    const candidate = anchor(word);
    return Boolean(candidate) && candidate === targetAnchor;
  });
}

/* ------------------------------------------------------------------------ */
/* Tidying                                                                    */
/*                                                                            */
/* Three artefacts show up in nearly every generation, all of them the model  */
/* trying to be helpful about layout the app already handles. Each is a       */
/* deterministic fix, so it is done here rather than asked for again:         */
/*                                                                            */
/*   the options inlined into the sentence AND supplied in `choices`, which   */
/*     renders the bracket twice — 「テスト（ が / を / に ）あります（ が /   */
/*     を / に ）」;                                                          */
/*   choices that label themselves, so the app's label doubles up — "a. a."; */
/*   the worked 例 arriving as question (1), where it is not a question at    */
/*     all but the section showing what an answer looks like.                 */
/* ------------------------------------------------------------------------ */

/** A run of the item's own options printed inside its sentence. */
function inlinedChoices(choices: string[]): RegExp {
  const alternatives = choices
    .map((choice) => choice.trim().replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
    .join("|");
  // 「（ が / を / に ）」 in either bracket, with the separators the papers use.
  return new RegExp(`[（(]\\s*(?:${alternatives})(?:\\s*[/／・|]\\s*(?:${alternatives}))+\\s*[）)]`, "g");
}

/** A label the model wrote onto its own option: "a.", "(b)", "③", "1.". */
const SELF_LABEL = /^\s*(?:[（(]?[a-eA-E][）).、]|[①-⑩]|\d[）).])\s*/;

/** A number the model wrote at the front of its own question, which the app
 * also prints: seen live as 「(1) 1. 毎日【部屋】をそうじします。」. */
const SELF_NUMBER = /^\s*(?:[（(]\s*\d{1,2}\s*[）)]|\d{1,2}\s*[.．、)）])\s*/;

/** An empty gap the model wrapped in a second pair of brackets: 「（ （　） ）」. */
const NESTED_GAP = /[（(]\s*[（(]\s*[　\s]*[）)]\s*[）)]/g;

const EXAMPLE_ROW = /^\s*(?:例|れい)\s*[）)．.、:：]/;

export function tidyQuiz(quiz: Quiz): { quiz: Quiz; tidied: number } {
  let tidied = 0;

  const sections = quiz.sections.map((section) => {
    const items = section.items
      // The 例 is section furniture, not an item: it shows the answer.
      .filter((item) => !EXAMPLE_ROW.test(item.question))
      .map((item) => {
        const choices = item.choices?.map((choice) => {
          const stripped = choice.replace(SELF_LABEL, "").trim();
          if (stripped !== choice.trim()) tidied += 1;
          return stripped || choice;
        });

        // The app numbers items itself, and collapses a doubly-bracketed gap.
        let question = item.question.replace(SELF_NUMBER, "").replace(NESTED_GAP, "（　）");
        let sentence = item.sentence?.replace(NESTED_GAP, "（　）");
        if (question !== item.question || sentence !== item.sentence) tidied += 1;

        if (choices && choices.length >= 2 && section.form === "bracket") {
          const inline = inlinedChoices(choices);
          const before = `${question}${sentence ?? ""}`;
          question = question.replace(inline, "（　）");
          sentence = sentence?.replace(inline, "（　）");
          if (`${question}${sentence ?? ""}` !== before) tidied += 1;
        }

        // Stripping a label must not orphan the answer from its options.
        const answer =
          choices && !choices.some((c) => c === item.answer)
            ? (choices.find((c) => item.answer.replace(SELF_LABEL, "").trim() === c) ??
              item.answer.replace(SELF_LABEL, "").trim())
            : item.answer;

        return { ...item, choices, question, sentence, answer };
      });

    return { ...section, items };
  });

  return { quiz: { ...quiz, sections }, tidied };
}

/** Why this item cannot be shown, or null when it can. */
export function itemFault(
  item: QuizItem,
  section: QuizSection,
  archetype?: SectionArchetype,
): string | null {
  const form = section.form ?? archetype?.form;

  if (!item.question.trim()) return "empty question";
  if (!item.answer.trim()) return "empty answer";
  if (!item.explanation.trim()) return "empty explanation";
  if (!item.review.trim()) return "empty review";
  // The review is the one line a student is meant to act on, and it has to be
  // findable in a book they own.
  if (/past paper|excerpt|source|material \d|handout/i.test(item.review)) {
    return `review points at the machinery: ${item.review.slice(0, 40)}`;
  }

  if (form === "maru_batsu" || item.type === "true_false") {
    if (!MARKS.test(item.answer.trim())) return `○× item answered ${item.answer.slice(0, 12)}`;
    if (item.choices?.length) return "○× item carries choices";
    return null;
  }

  if (form === "bracket" || form === "lettered" || item.type === "multiple_choice") {
    const choices = item.choices ?? [];
    if (choices.length < 2) return "choice item with fewer than two options";
    // The count the paper actually prints for this section. A three-option
    // a〜c section with four options is not the section the student sat.
    if (archetype?.choices && choices.length !== archetype.choices) {
      return `${choices.length} options where the paper prints ${archetype.choices}`;
    }
    const seen = new Set(choices.map(bare));
    if (seen.size !== choices.length) return "duplicate options";
    if (choices.some((choice) => !choice.trim())) return "blank option";
    // Exactly one correct answer, and it has to be on the list.
    const matches = choices.filter((choice) => bare(choice) === bare(item.answer));
    if (matches.length === 0) return `answer ${item.answer.slice(0, 16)} is not among the options`;
    if (matches.length > 1) return "more than one option matches the answer";
    return null;
  }

  // Written answers.
  if (item.choices?.length) return "written item carries choices";
  if (section.word_bank?.length && !fromBank(item.answer, section.word_bank)) {
    return `answer ${item.answer.slice(0, 16)} is not a form of any word in the bank`;
  }
  return null;
}

/** Drop every item that cannot be shown, and any section left empty.
 *
 * Word-bank sections get one extra rule that only makes sense across a whole
 * section: the paper says each word may be used once, so an answer drawn from
 * a bank entry already used earlier in the section is dropped too.
 */
export function validateQuiz(
  quiz: Quiz,
  blueprint: SectionArchetype[] = [],
): { quiz: Quiz; rejected: Rejection[] } {
  const rejected: Rejection[] = [];

  const sections = quiz.sections
    .map((section, sectionIndex) => {
      const archetype = blueprint[sectionIndex];
      const usedBankWords = new Set<string>();

      const items = section.items.filter((item, itemIndex) => {
        const fault = itemFault(item, section, archetype);
        if (fault) {
          rejected.push({ section: sectionIndex, item: itemIndex, reason: fault });
          return false;
        }
        if (section.word_bank?.length) {
          // Keyed on the same anchor fromBank matches on, so 行きます and
          // 行った count as the one bank word they both are.
          const text = bare(item.answer);
          const key = /^[一-鿿]/.test(text) ? text.slice(0, 1) : text.slice(0, 2);
          if (usedBankWords.has(key)) {
            rejected.push({
              section: sectionIndex,
              item: itemIndex,
              reason: "a bank word the paper says may be used once was used twice",
            });
            return false;
          }
          usedBankWords.add(key);
        }
        return true;
      });

      return { ...section, items };
    })
    .filter((section) => section.items.length > 0);

  return { quiz: { ...quiz, sections }, rejected };
}
